function [fitresult, gof] = poly2fit_withplot(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Jan-2021 20:15:41


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'poly2' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData);
h(1).Color = 'k';
h(2).Color =  [0 0 204]./255;
h(2).LineWidth = 1;
 legend( h, 'y vs. x', 'poly2', 'Location', 'NorthEast' );
% Label axes
ylabel ('TIR temp (C)')
xlabel ('Depth (cm)')
grid on


