function [fitresult, gof] = powfit_withplot(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Jan-2021 20:16:24


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [283.923292014104 0.00521027700961243];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData);
h(1).Color = 'k';
h(2).Color = [255 128 0]./255;
h(2).LineWidth = 1;
legend( h, 'y vs. x', 'pow', 'Location', 'SouthEast' );
% Label axes
ylabel ('TIR temp (C)')
xlabel ('Depth (cm)')
grid on


